### ISSUE TITLE
Running FormulaCSV

### ISSUE THREAD

**Issue by henjolstad** [Elteoremadebeethoven/MyAnimations#2]
Hi. I'm very new to both manim and python and have a question to the FormulaCSV function. 

When I render with -ps, the media files doesn't save to media/TeX folder, but piles up in manim-master folder. I noticed that adding "def construct (self):" fixes this problem, but when I do this and render with -ps, I only get a black picture.

I appreciate any help/feedback.

**Comment by Elteoremadebeethoven** [comment]
That scene is not intended to export images, but .csv of the formulas, and you must use the February 3 version to use it.
