### ISSUE TITLE
Replace Code to Create Grid

### ISSUE THREAD

**Issue by konothonaios** [Elteoremadebeethoven/MyAnimations#5]
Just replace:

`label = Text(f"{coord_point}",font="Arial",stroke_width=0).scale(self.labels_scale)`

with

`label = TextMobject(f"{coord_point}",font="Arial",stroke_width=0).scale(self.labels_scale)`

in line 72.

**Comment by Elteoremadebeethoven** [comment]
That's only valid for the February 3 release, I've already made the comment on the video, thanks.
